services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SwaggerUrl=https://localhost:5002
      - Redis__ConnectionString=redis:6379
    ports:
      - "5000:8081"
    depends_on:
      - backend
      # - redis
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Redis__ConnectionString=redis:6379
      - CosmosDb__Endpoint=https://cosmosdb:8081
      - CosmosDb__PrimaryKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - CosmosDb__DatabaseName=MyDatabase
      - CosmosDb__ContainerName=WeatherForecasts
      - SqlServer__ConnectionString=Server=sqlserver,1433;Database=WeatherForecastDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    ports:
      - "5001:8080"
      - "5002:8081"
    # depends_on:
      # - redis
      # - sqlserver
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  # redis:
  #   ports:
  #     - "6379:6379"
  # sqlserver:
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourStrong@Passw0rd
  #     - MSSQL_PID=Express
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserver-data:/var/opt/mssql
  #     - ./backend/sql-init:/usr/src/mssql-init
  # cosmosdb:
  #   ports:
  #     - "8081:8081"
  #     - "8901:8901"
  #     - "10250:10250"
  #     - "10350:10350"
  #   environment:
  #     - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
  #     - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true