services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: backend/Dockerfile
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   volumes:
  #     - sqlserver-data:/var/opt/mssql
  #     - ./database:/usr/src/mssql-init
  # cosmosdb:
  #   image: mcr.microsoft.com/cosmosdb/linux
  #   volumes:
  #     - cosmosdb-data:/data
volumes:
  redis-data:
  # sqlserver-data:
  # cosmosdb-data: