services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: backend/Dockerfile
#   cosmosdb:
#     image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
#     volumes:
#       - cosmosdb-data:/data
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
volumes:
  # cosmosdb-data:
  redis-data:
  